language: python
python:
  - 3.3
  - 3.4

install:
  # Use the latest version.
  - pip install -U nose mock
  # For coverage reports
  - pip install coverage coveralls

  - python setup.py develop
  - python setup.py build_py

script:
  - python dev_tools/coverage_runner.py
after_success:
  - coveralls --rcfile=dev_tools/.coveragerc
